export default [
  'None',
  'African and African American Studies',
  'Anthropology',
  'Archaeology',
  'Astrophysics',
  'Celtic Languages and Literatures',
  'Chemistry',
  'Classics',
  'Comparative Literature',
  'Computer Science',
  'Theater, Dance, and Media',
  'Earth and Planetary Sciences',
  'East Asian Studies',
  'Economics',
  'Energy and Environment',
  'English',
  'Environmental Science and Public Policy',
  'Ethnicity, Migration, Rights',
  'Folklore and Mythology',
  'Germanic and Scandinavian Studies',
  'Global Health and Health Policy',
  'Government',
  'History',
  'History of Art and Architecture',
  'History of Science',
  'Human Evolutionary Biology',
  'Integrative Biology',
  'European History, Politics, and Societies',
  'Linguistics',
  'Mathematical Sciences',
  'Medieval Studies',
  'Microbial Sciences',
  'Mind/Brain/Behavior',
  'Molecular and Cellular Biology',
  'Music',
  'Near Eastern Languages and Civilizations',
  'Neurobiology',
  'Philosophy',
  'Physics',
  'Psychology',
  'Comparative Study of Religion',
  'Romance Languages and Literatures',
  'Russia, Eastern Europe, and Central Asia',
  'Slavic Languages and Literatures',
  'Sociology',
  'South Asian Studies',
  'Statistics',
  'Visual and Environmental Studies',
  'Studies of Women, Gender, and Sexuality'
]
